config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'jobs#index'
  resources :jobs, only: [:index]
  resources :industries, only: [:index]
   
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
   # before_action :basic_auth
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(
      :sign_up, keys: [:nickname, :email, :birth_date, :first_name, :last_name, :first_name_kana, :last_name_kana,:university]
    )
  end
end

app/controllers/industries_controller.rb
class IndustriesController < ApplicationController
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    
  end
end

def show
  
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/industries_helper.rb
module IndustriesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/industries/index.html.erb
<div class="page_title">
  <div class="base_inner">
    <h2>業界・職種の一覧</h2>
  </div>
</div>
<div class="smartphone">
 <%= image_tag "smartphone.jpg" %>
</div>

<div class="title_container">
<div class="left_container">
<ul>
<li class="toc-page">金融業界</li>
<li class="toc-page">建設・不動産業界</li>
<li class="toc-page">運輸・物流業界</li>
<li class="toc-page">流通・小売業界</li>
<li class="toc-page">IT業界</li>
<li class="toc-page">マスコミ・メディア・広告業界</li>
<li class="toc-page">エネルギー・資源業界</li>
</ul>
</div>

<div class="right_container">
<ul>
<li class="toc-page">自動車・機械業界</li>
<li class="toc-page">電気・精密機器業界</li>
<li class="toc-page">食品・飲食業界</li>
<li class="toc-page">生活用品業界</li>
<li class="toc-page">サービス業界</li>
<li class="toc-page">エンタメ業界</li>
</ul>
</div>
</div>

<div class="btn-contents">
   <%=link_to 'もどる', root_path, class:"back-btn" %>
 </div>

app/views/jobs/index.html.erb
<header class= "top-page-header">
<div class="search-bar-contents">
  <%= link_to image_tag("syuuapp-logo.png", class: "syuuapp-logo"),"/" %>
  <form class="search-form" action="#">
      <input class='input-box' placeholder='キーワードから探す'>
      <button class="search-button">
        <%= image_tag "search.png", class:"search-icon" %>
      </button>
    </form>
</div>
<div class='nav'>
    <ul class='lists-left'>
      <li><%= link_to '業界・職種を見る', industries_path, class: "industry-list" %></li>
      
    </ul>
    <ul class='lists-right'>
      <% if user_signed_in? %>
       <li><%=link_to current_user.nickname, "#", class: "user-nickname" %></li> 
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li> 
      <% else %>
      <li><%= link_to 'ログイン', new_user_session_path, class: "login"%></li>
      <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up"%></li>
      <% end %>
    </ul>
  </div>
</header>

<div class="main">
<div class='title-contents'>
    <h2 class='service-title'>
      ラクラク求人検索
    </h2>
    <p class='service-explain'>
      気になる業界・職種を入力するだけであなたに合った求人が見つかる！
    </p>
    <p class='service-explain'>
      就活アプリです
    </p>
  </div>
  <%# FURIMAが選ばれる3つの理由部分 %>
  <div class='select-reason-contents'>
    <h2 class='title'>
      就アプの3つの強み
    </h2>
    <ul class='reason-lists'>
      <li class='list'>
        <%= image_tag "top1.png", class:"list-pict" %>
        <%# <span class='reason-list-number'>1</span> %>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>お手軽</span>
          求人検索が可能
        </h3>
        <p class='reason-list-description'>
          あなたが気になる求人が見つかる！
        </p>
      </li>
      <li class='list'>
        <%= image_tag "top2.png", class:"list-pict" %> 
        <%# <span class='reason-list-number'>2</span> %>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>企業研究</span>
          がしやすい
        </h3>
        <p class='reason-list-description'>
          業界・職種の理解を深めて、面接力UP！
        </p>
      </li>
      <li class='list'>
         <%= image_tag "top3.png", class:"list-pict" %> 
        <%# <span class='reason-list-number'>3</span> %>
        <h3 class='reason-list-text'>
          <span class='reason-list-blue-text'>面接</span>
          の記録がとれる
        </h3>
        <p class='reason-list-description'>
          面接を記録することでPDCAを回そう！
        </p>
      </li>
    </ul>
  </div>
  <%# /就アプが選ばれる3つの理由部分 %>
<div class="ad-contents"> 
<%# <%= image_tag "dream-job.jpg", class:"dream-job" %> 
  <h2 class='ad-title'>
      会員数日本一位
    </h2>
    <p class='ad-explain'>
      FURIMAは、フリマアプリで最も人気。
    </p>
    <p class='ad-explain'>
      出品・購入回数も業界最多です！
    </p>
    <p class='ad-explain'>
      ほしかったあの商品に出会えるかもしれません。
    </p> 
 </div>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>就アプ</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>